apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "microapp.name" . }}
    app.kubernetes.io/component: web