apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bW9uZ291c2Vy   # base64("mongouser")
  mongo-root-password: cGFzc3dvcmQxMjM= # base64("password123")
