apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: {{ .Values.mongodb.username | b64enc }}
  mongo-root-password: {{ .Values.mongodb.password | b64enc }}
