apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microapp.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.api.env.dbHost | quote }}
  DB_PORT: {{ .Values.api.env.dbPort | quote }}
  DB_NAME: {{ .Values.api.env.dbName | quote }}
  DB_USER: {{ .Values.api.env.dbUser | quote }}