apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microapp.labels" . | nindent 4 }}
spec:
  ports:
    - name: postgres
      port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "microapp.name" . }}
    app.kubernetes.io/component: db
  type: ClusterIP