apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microapp.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}