# "This workflow runs a custom GitHub Action that greets the user."
name: Advance task 1 - test if publish.yml

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run my custom action
        uses: OmerBarzilay16/my-github-action@main
        with:
          name: Omer
