# "This workflow runs a custom GitHub Action that greets the user."
name: Advance task 1 - Create my own action.yml

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run my custom action
        uses: ./my-github-action
        with:
          name: Omer
