name: Generate ASCII Art

on: workflow_dispatch
#on: push

jobs:
  generate_ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Cowsay
        run: sudo apt-get install -y cowsay

      - name: Execute Cowsay
        run: cowsay -f dragon "Hello Nitro Hazinnnnnnnnn dragon" >> dragon.txt

      - name: Test file existence
        run: grep -i "dragon" dragon.txt || echo "Dragon not found in file"

      - name: Display ASCII Art
        run: cat dragon.txt