name: matrix-practice

on: workflow_dispatch

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        image: [hello-world, busybox]
        exclude:
          - os: windows-latest
            image: busybox
        include:
          - os: ubuntu-latest
            image: alpine
    runs-on: ${{ matrix.os }}
    steps:
        - name: print docker info
          run: |
            docker info
            docker version
        
        - name: run docker image
          run: docker run --rm ${{ matrix.image }}