name: Practice - CI Workflow for a Node.js Project

on: 
   push:
    branches:
      - main
   pull_request:
    branches:
      - main
concurrency:
  group: 'node-ci-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
       node-versions: [14, 16, 18]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-versions }}
          cache: 'npm'

      - name: test
        run: |
          npm install
          npm test

      - name: Print run number
        run: echo "Run number is ${{ github.run_number }}"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Build Project
        run: echo "Not real app""
      
    
        
        