name: Practice expressions&timeouts

on: workflow_dispatch

jobs:
  expressions_test_job:
    if: ${{ github.run_number }} > 0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: print the run number
        run: echo "The run number is ${{ github.run_number }}"

  timeout-minutes_test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Wait for 5 minutes
        run: sleep 300