name: testing needs & concurrency

on: workflow_dispatch

jobs:
  context_test_job:
    runs-on: ubuntu-latest
    steps:

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump secret context
        env:
          SECRET_CONTEXT: ${{ toJson(secrets) }}
        run: echo "$SECRET_CONTEXT"

  context_test_job2:
    concurrency:
        group: test-group
        cancel-in-progress: true
    needs: context_test_job
    runs-on: ubuntu-latest
    steps:
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Sleep for 1000 seconds
        run: sleep 1000