name: Task 4 - Check Day of the Week and Run Conditionals

on: workflow_dispatch

jobs:
  get-day:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Day of the Week and Set Environment Variable
        run: |
          DAY=$(date +%A)
          echo "day=$DAY" >> $GITHUB_OUTPUT
     

  weekday-action:   
    runs-on: ubuntu-latest
    needs: get-day
    if: ${{ needs.get-day.outputs.weekday != 'Saturday' && needs.get-day.outputs.weekday != 'Sunday' }}
    steps:
      - name: Run on Weekdays
        run: echo "It's a weekday! Running the action."


  weekend-action:
    runs-on: ubuntu-latest
    needs: get-day
    if: ${{ env.day == 'Saturday' || env.day == 'Sunday' }}
    steps:
      - name: Run on Weekends
        run: echo "It's the weekend! Skipping the action."