name: Task 1 - CI Workflow for a Node.js Project

on: 
   push:
    branches:
      - main
   pull_request:
    branches:
      - main
concurrency:
  group: 'node-ci-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
       node-versions: [14, 16, 18]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
    
      - name: Set up Node.js
        run: | 
          echo "Setting up Node.js version ${{ matrix.node-versions }}"
          echo "Not a real app"


  build:
    runs-on: ubuntu-latest
    needs: test
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Build Project
        run: echo "Not a real app"
      
    
        
        