name: Task 4 - Check Day of the Week and Run Conditionals

on: workflow_dispatch

jobs:
  get-day:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Day of the Week
        id: get_day
        run: |
          echo "day=$(date +%A)" >> $GITHUB_ENV
          echo "Current day is: $GITHUB_ENV"

  weekday-action:
    runs-on: ubuntu-latest
    needs: get-day
    if: ${{ env.day != 'Saturday' && env.day != 'Sunday' }}
    steps:
      - name: Run on Weekdays
        run: echo "It's a weekday! Running the action."


  weekend-action:
    runs-on: ubuntu-latest
    needs: get-day
    if: ${{ env.day == 'Saturday' || env.day == 'Sunday' }}
    steps:
      - name: Run on Weekends
        run: echo "It's the weekend! Skipping the action."